apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tzdr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0027-tenant/tkrw-pr712-0075-0027-app/devfile-sample-tzdr@sha256:eb4fc95fc267a5dea65205e5ade5b8d0addace3bb21dd92d085109f204a48065
        name: my-nodejs
        resources: {}
status: {}
